title: Landing Jekyll
description: Jekyll is landing to the earth!    
# lang: ko_KR

sass:
   sass_dir: node_modules/bootstrap/scss
   # sass_dir: _scss
   # load_paths:
   #   - _scss
   #   - node_modules/bootstrap/scss
   style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  
plugins:
  - jekyll-seo-tag
  