sass:
   sass_dir: bower_components/bootstrap/scss
   # sass_dir: _scss
   style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bower_components
  - bower.json